name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        arch: [i386, arm64, armhf]
    steps:   
    - name: Install Cross-Compile Support
      uses: cyberjunk/gha-ubuntu-cross@feature/improvements
      with:
        arch: ${{ matrix.arch }}    
    - name: Install a package (libx11-dev)
      env:
        arch: ${{ matrix.arch }} 
      run: sudo apt-get install libx11-dev:$arch
